### ISSUE TITLE
script returns error 256 mktemp -d fails

### ISSUE THREAD

**Issue by dchersey** [wmanley/git-meld#1]
I have a Mac running 10.6.7, and I installed this script along with meld. 

I cd to my project directory, and run git meld master..<commit-to-compare>

The script returns "mktemp -d failed with exit code 256 at /Users/david/bin/git-meld.pl line 27."
I don't understand why this fails: mktemp -d works fine on the command line. 
I modified the script to hardcode the temp directory as /Users/<me>/tmp" and the script worked fine.

Just thought you should know....

David

**Comment by wmanley** [comment]
Thanks David.  I've committed a fix that hopefully fixes this issue could you give the latest a try?

Thanks

Will

**Comment by dchersey** [comment]
Thanks, that did the trick!
