### ISSUE TITLE
git-meld question

### ISSUE THREAD

**Issue by edwin-bluekite** [wmanley/git-meld#21]
I want to meld a diff between my current repo and my origin after a fetch something like git diff master origin/master
Is this possible with git-meld?

**Comment by wmanley** [comment]
Yes, you use got meld just like git diff. If you are using git >= 1.7.11 I would recommend using the built in support. So you would write:

   git difftool --dir-diff master origin/master

**Comment by edwin-bluekite** [comment]
Thanks, I did it doing this:
git config --global diff.tool meld
and then
git difftool  myrepo origin/remoterepo
