### ISSUE TITLE
Diff of a commit?

### ISSUE THREAD

**Issue by nbigaouette** [wmanley/git-meld#3]
Thanks for git-meld. It's an amazing tool!

Would it be possible to get the diff of a **single** commit? For example:
git meld 3aed88f540c08b2fb854476f95d4db27d9600f79
Which would bring the diff of that exact commit?

Right now it shows the diff **since** that commit...

Thanks!

**Comment by wmanley** [comment]
git meld accepts the same options as git diff whereas what you're describing sounds more like git show.  One way of doing this would be

```
git meld 3aed88f^ 3aed88f
```

which I use a lot. It's a little verbose but I think there is real value in git meld mirroring git diff as closely as possible.

**Comment by wmanley** [comment]
I find when doing code reviews it can be beneficial to have the second "revision" in the comparison be the working directory rather than a git revision which can only be displayed read-only.  This means you can edit and save files during the review.  You do this with

```
git checkout -b review_comments 3aed88f
git meld HEAD^
```
