### ISSUE TITLE
git archive fails if I'm not in the repo root dir

### ISSUE THREAD

**Issue by parren** [wmanley/git-meld#5]
Because the path list is relative to the repo root.

**Comment by parren** [comment]
I have a very simple fix, but thanks to Google's policy, I have to get it cleared first.

**Comment by wmanley** [comment]
Ah ha, I was having difficulty reproducing this bug until I read in `git help config` under the item `alias.*`:

```
       If the alias expansion is prefixed with an exclamation point, it
       will be treated as a shell command. For example, defining "alias.new
       = !gitk --all --not ORIG_HEAD", the invocation "git new" is
       equivalent to running the shell command "gitk --all --not
       ORIG_HEAD". Note that shell commands will be executed from the
       top-level directory of a repository, which may not necessarily be
       the current directory.
```

Presumably you're invoking git-meld directly.  I will write an automated test for this bug and then merge your fix

**Comment by wmanley** [comment]
Your patch fixed the issue.  Thanks Peter!

**Comment by parren** [comment]
Actually, I simply invoke "git meld", which automagically calls any
git-meld on the path.
On Nov 14, 2011 12:43 AM, "wmanley" <
reply@reply.github.com>
wrote:

**Comment by wmanley** [comment]
Interesting, what version of git are you using?  How have you set up your "git meld" alias?

**Comment by parren** [comment]
On Tue, Nov 15, 2011 at 1:38 AM, wmanley
reply@reply.github.com
wrote:

> Interesting, what version of git are you using?  How have you set up your "git meld" alias?

git version 1.7.3.1

As for the alias, I think I didn't set one up. But I have now since I
discovered that Google has its own internal git-meld script.
--peter
